# Generated by Django 4.2.1 on 2023-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='replyCount',
            field=models.IntegerField(default=0),
        ),
    ]
